// Angel
export const AGREGAR_ANGEL_INFO = "AGREGAR_ANGEL_INFO";

// Auth
export const REGISTRAR_USUARIO = "REGISTRAR_USUARIO";
export const LOGIN_USUARIO = "LOGIN_USUARIO";
export const LOGOUT_USUARIO = "LOGOUT_USUARIO";
export const LOGIN_GOOGLE = "LOGIN_GOOGLE";

// Users
export const GUARDAR_USUARIO = "GUARDAR_USUARIO";
export const EDITAR_PERFIL_GUARDIAN = "EDITAR_PERFIL_GUARDIAN";
