// Auth
export const REGISTRAR_USUARIO = 'REGISTRAR_USUARIO';
export const LOGIN_USUARIO = 'LOGIN_USUARIO';
export const LOGOUT_USUARIO = 'LOGOUT_USUARIO';
export const LOGIN_GOOGLE = 'LOGIN_GOOGLE';

// Users
export const GUARDAR_USUARIO = 'GUARDAR_USUARIO';
export const EDITAR_PERFIL_GUARDIAN = 'EDITAR_PERFIL_GUARDIAN';

// Angel
export const AGREGAR_ANGEL_INFO = 'AGREGAR_ANGEL_INFO';
export const AGREGAR_ANGEL_CONTACT = 'AGREGAR_ANGEL_CONTACT';
export const AGREGAR_ANGEL_DISEASES = 'AGREGAR_ANGEL_DISEASES';
export const AGREGAR_ANGEL = 'AGREGAR_ANGEL';
export const EDITAR_ANGEL_INFO = 'EDITAR_ANGEL_INFO';
export const EDITAR_ANGEL_CONTACT = 'EDITAR_ANGEL_CONTACT';
export const OBTENER_ANGELES = 'OBTENER_ANGELES';
export const OBTENER_ANGEL = 'OBTENER_ANGEL';
